all: fork_test

fork_test: fork_test.cpp
	g++ fork_test.cpp -o fork_test

chrono_test: chrono_test.cpp
	g++ chrono_test.cpp -o chrono_test

multi_process: multi_process.cpp
	g++ multi_process.cpp -o multi_process

multi_thread_cal: multi_thread_cal.cpp
	g++ multi_thread_cal.cpp -o multi_thread_cal

multi_thread: multi_thread.cpp
	g++ multi_thread.cpp -o multi_thread

clean:
	rm *.o
