#define BUFFER_SIZE          1024
#define ENABLE_HTTP_RESPONSE 1
#define CONN_LIST_SIZE       128

// #define ENABLE_LOG 1

#define ENABLE_ARRAY_KVSENGINE  1
#define ENABLE_RBTREE_KVSENGINE 2  
#define ENABLE_HASH_KVSENGINE 3

#define NETWORK_EPOLL 0
#define NETWORK_NTYCO 1
#define NETWORK_IORTING 2

#define ENABLE_NETWORK_SELECT   NETWORK_EPOLL
#define ENABLE_KVSENGINE_SELECT ENABLE_RBTREE_KVSENGINE